import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut, createUserWithEmailAndPassword, updateProfile } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, doc, getDoc, setDoc, updateDoc, deleteDoc, query, orderBy, serverTimestamp, runTransaction } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyDXfMK8nxFQ9-wbazPYqgPmF58QFS_Y1Vs",authDomain:"mystical-wellness.firebaseapp.com",projectId:"mystical-wellness",storageBucket:"mystical-wellness.firebasestorage.app",messagingSenderId:"859227928719",appId:"1:859227928719:web:88f098c46bed52e44318fa",measurementId:"G-6XV6XJX2MX"};
const ADMIN_EMAILS=new Set(["mysticalwellness26@gmail.com","mysticalwellness26recovery@gmail.com"]);
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig); const auth=getAuth(app); const db=getFirestore(app); export {auth,db};
export const watchAuth=cb=>onAuthStateChanged(auth,cb); export const logOut=()=>signOut(auth); export const isAdminEmail=email=>ADMIN_EMAILS.has(String(email||"").trim().toLowerCase());
export async function getAllOrders(){const s=await getDocs(query(collection(db,"orders"),orderBy("createdAt","desc")));return s.docs.map(x=>({id:x.id,...x.data()}));}
export async function getAllUsers(){const s=await getDocs(query(collection(db,"users"),orderBy("createdAt","desc")));return s.docs.map(x=>({id:x.id,...x.data()}));}
export async function updateOrderStatus(id,status){if(!id)throw new Error("Missing order ID.");await updateDoc(doc(db,"orders",id),{status,updatedAt:serverTimestamp()});}
export const markOrderCancelled=id=>updateOrderStatus(id,"Cancelled");
export async function markOrderCompletedAndAwardPoints(id){if(!id)throw new Error("Missing order ID.");await runTransaction(db,async t=>{const ref=doc(db,"orders",id),snap=await t.get(ref);if(!snap.exists())throw new Error("Order not found.");const o=snap.data(),updates={status:"Completed",completedAt:serverTimestamp(),updatedAt:serverTimestamp()};if(o.uid&&!o.pointsAwarded){const uref=doc(db,"users",o.uid),us=await t.get(uref),earned=Math.max(0,Math.floor(Number(o.subtotal||0)));if(us.exists()){t.update(uref,{points:Number(us.data().points||0)+earned});updates.pointsAwarded=true;updates.pointsAwardedAmount=earned;}}t.update(ref,updates);});}
export async function markRewardCodeUsed(code){code=String(code||"").trim().toUpperCase();if(!code)throw new Error("A reward code is required.");const ref=doc(db,"rewardCodes",code),s=await getDoc(ref);if(!s.exists())throw new Error("Reward code not found.");if(s.data().status==="used")throw new Error("This reward code was already used.");await updateDoc(ref,{status:"used",usedAt:serverTimestamp(),usedBy:auth.currentUser?.email||"unknown"});}
export async function adjustUserPoints(uid,delta,reason,adminEmail){if(!uid)throw new Error("Missing customer ID.");if(!Number.isFinite(Number(delta)))throw new Error("Point change must be a number.");if(!reason?.trim())throw new Error("A reason is required.");await runTransaction(db,async t=>{const r=doc(db,"users",uid),s=await t.get(r);if(!s.exists())throw new Error("Customer not found.");t.update(r,{points:Math.max(0,Number(s.data().points||0)+Number(delta))});});await addDoc(collection(db,"customerAudits"),{action:"Points adjusted",uid,adminEmail:adminEmail||auth.currentUser?.email||"unknown",note:reason.trim(),details:`Point change: ${Number(delta)>0?"+":""}${Number(delta)}.`,createdAt:serverTimestamp()});}
export async function getCustomerAudits(){const s=await getDocs(query(collection(db,"customerAudits"),orderBy("createdAt","desc")));return s.docs.map(x=>({id:x.id,...x.data()}));}
export async function updateCustomerProfileWithAudit(uid,updates,note,adminEmail){if(!uid)throw new Error("Missing customer ID.");if(!note?.trim())throw new Error("A note is required.");const r=doc(db,"users",uid),s=await getDoc(r);if(!s.exists())throw new Error("Customer not found.");const before=s.data();await updateDoc(r,updates);await addDoc(collection(db,"customerAudits"),{action:"Customer profile updated",uid,adminEmail:adminEmail||auth.currentUser?.email||"unknown",note:note.trim(),details:`Updated ${Object.keys(updates).join(", ")} for ${before.email||uid}.`,before,after:{...before,...updates},createdAt:serverTimestamp()});}
export async function createCustomerAccount({name,phone,email,password,note}){if(!name||!email||!password)throw new Error("Name, email, and temporary password are required.");if(password.length<6)throw new Error("The temporary password must contain at least 6 characters.");if(!note?.trim())throw new Error("A note is required.");const normalized=email.trim().toLowerCase(),secondary=getAuth(initializeApp(firebaseConfig,`customer-${Date.now()}`)),adminEmail=auth.currentUser?.email||"unknown";try{const c=await createUserWithEmailAndPassword(secondary,normalized,password);await updateProfile(c.user,{displayName:name.trim()});await setDoc(doc(db,"users",c.user.uid),{name:name.trim(),phone:phone?.trim()||"",email:normalized,address:"",points:0,activeReward:null,createdAt:serverTimestamp()});await addDoc(collection(db,"customerAudits"),{action:"Customer account created",uid:c.user.uid,adminEmail,note:note.trim(),details:`Created customer account for ${normalized}.`,createdAt:serverTimestamp()});return {uid:c.user.uid,email:normalized};}finally{await signOut(secondary).catch(()=>{});}}
export async function updateCustomerEmail(uid,email,note){if(!uid||!email?.trim()||!note?.trim())throw new Error("Customer ID, email, and note are required.");const r=doc(db,"users",uid),s=await getDoc(r);if(!s.exists())throw new Error("Customer profile not found.");const old=s.data().email||"",next=email.trim().toLowerCase();await updateDoc(r,{email:next});await addDoc(collection(db,"customerAudits"),{action:"Customer profile email updated",uid,adminEmail:auth.currentUser?.email||"unknown",note:note.trim(),details:`Profile email changed from ${old} to ${next}. The Firebase Authentication login email must be changed separately in Firebase Console.`,createdAt:serverTimestamp()});}
export async function deleteCustomerAccount(uid,note){if(!uid||!note?.trim())throw new Error("Customer ID and note are required.");const r=doc(db,"users",uid),s=await getDoc(r);if(!s.exists())throw new Error("Customer profile not found.");const customer=s.data();await addDoc(collection(db,"customerAudits"),{action:"Customer profile removed",uid,adminEmail:auth.currentUser?.email||"unknown",note:note.trim(),details:`Removed Firestore profile for ${customer.email||uid}. Delete the Authentication account separately in Firebase Console.`,removedProfile:customer,createdAt:serverTimestamp()});await deleteDoc(r);}
